<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC9cii1s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC9cii1s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC9cii1s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC9cii1s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC9cii1s\App_KernelDevDebugContainer([
    'container.build_hash' => 'C9cii1s',
    'container.build_id' => '6353dd7d',
    'container.build_time' => 1626045726,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC9cii1s');
